import {
  Search,
  SquareLibrary,
  Bug,
  ClipboardClock,
  Gauge,
  BadgePlus,
  MonitorUp,
  Link,
  LockKeyhole,
  EyeOff,
  Eye,
  LayoutDashboard,
  FolderKanban,
  ListChecks,
  CircleDot,
  BarChart3,
  Clock,
  Settings,
  Bell,
  HelpCircle,
  ChevronLeft,
  Plus,
  Users,
  Calendar,
  CalendarPlus,
  MoreHorizontal,
  SlidersHorizontal,
  Leaf,
  Star,
  Rocket,
  Smartphone,
  Box,
  Layers,
  MoreVertical,
  ChevronRight,
  Check,
  Inbox,
  CheckSquare,
  ListTodo,
  Map,
  Clock3,
  Sparkles,
  Filter,
  KanbanSquare,
  ArrowUpRight,
  RefreshCw,
  Zap,
  User,
  Minus,
  Equal,
  CheckCircle2,
  AlertCircle,
  Pencil,
  ClipboardList,
  Activity,
  Maximize2,
  ChevronsUp,
  ChevronUp,
  ChevronDown,
  ChevronsDown,
  Timer,
  Ban,
  Columns,
  CircleSlash2,
  Workflow,
  LayoutGrid,
  ArrowUpCircle,
  GitBranch,
  GitCommit,
  Code,
  UserPlus,
  Share2,
  FileText,
  Trash2,
  Shield,
  X,
  UserX,
  Bookmark,
  CornerDownLeft,
  MousePointer2,
  Edit3,
  MinusSquare,
  Paperclip,
  Briefcase,
  PartyPopper,
  AlertTriangle,
  Sun,
  Moon,
  PieChart,
  Menu,
  Image,
  Camera,
  Folder,
  Flag,
  Hash,
  ArrowRight,
  PanelRightClose,
  PanelRightOpen,
  CalendarX2,
  Lightbulb,
  Cloud,
  Minimize2,
  CheckCircle,
  FolderTree,
  Save,
  Building2,
  Mail,
  HardDrive,
  Send,
  Info,
  XCircle,
  Edit2,
  LogIn,
  TrendingUp,
  TrendingDown,
  LogOut,
  Server,
  Tag,
  LayoutList,
  UserCheck,
  GripVertical,
  MessageSquare
} from 'lucide-react';

export const Icons = {
  search: Search,
  squareLibrary: SquareLibrary,
  bug: Bug,
  clipboardClock: ClipboardClock,
  gauge: Gauge,
  badgePlus: BadgePlus,
  monitorUp: MonitorUp,
  link: Link,
  lockKeyhole: LockKeyhole,
  eyeOff: EyeOff,
  eye: Eye,
  layoutDashboard: LayoutDashboard,
  folderKanban: FolderKanban,
  listChecks: ListChecks,
  circleDot: CircleDot,
  barChart3: BarChart3,
  clock: Clock,
  settings: Settings,
  bell: Bell,
  helpCircle: HelpCircle,
  chevronLeft: ChevronLeft,
  image: Image,
  camera: Camera,
  plus: Plus,
  users: Users,
  calendar: Calendar,
  calendarPlus: CalendarPlus,
  moreHorizontal: MoreHorizontal,
  slidersHorizontal: SlidersHorizontal,
  leaf: Leaf,
  star: Star,
  rocket: Rocket,
  smartphone: Smartphone,
  box: Box,
  layers: Layers,
  moreVertical: MoreVertical,
  chevronRight: ChevronRight,
  check: Check,
  inbox: Inbox,
  checkSquare: CheckSquare,
  listTodo: ListTodo,
  map: Map,
  clock3: Clock3,
  sparkles: Sparkles,
  filter: Filter,
  kanbanSquare: KanbanSquare,
  arrowUpRight: ArrowUpRight,
  refreshCw: RefreshCw,
  zap: Zap,
  user: User,
  minus: Minus,
  equal: Equal,
  checkCircle2: CheckCircle2,
  alertCircle: AlertCircle,
  pencil: Pencil,
  clipboardList: ClipboardList,
  activity: Activity,
  maximize2: Maximize2,
  chevronsUp: ChevronsUp,
  chevronUp: ChevronUp,
  chevronDown: ChevronDown,
  chevronsDown: ChevronsDown,
  gitCommit: GitCommit,
  timer: Timer,
  ban: Ban,
  columns: Columns,
  circleSlash2: CircleSlash2,
  workflow: Workflow,
  layoutGrid: LayoutGrid,
  arrowUpCircle: ArrowUpCircle,
  gitBranch: GitBranch,
  code: Code,
  userPlus: UserPlus,
  share2: Share2,
  fileText: FileText,
  trash2: Trash2,
  shield: Shield,
  x: X,
  userX: UserX,
  bookmark: Bookmark,
  cornerDownLeft: CornerDownLeft,
  mousePointer2: MousePointer2,
  edit3: Edit3,
  minusSquare: MinusSquare,
  paperclip: Paperclip,
  briefcase: Briefcase,
  partyPopper: PartyPopper,
  alertTriangle: AlertTriangle,
  sun: Sun,
  moon: Moon,
  pieChart: PieChart,
  menu: Menu,
  folder: Folder,
  flag: Flag,
  hash: Hash,
  arrowRight: ArrowRight,
  panelRightClose: PanelRightClose,
  panelRightOpen: PanelRightOpen,
  calendarX2: CalendarX2,
  lightbulb: Lightbulb,
  cloud: Cloud,
  minimize2: Minimize2,
  checkCircle: CheckCircle,
  folderTree: FolderTree,
  save: Save,
  building2: Building2,
  mail: Mail,
  hardDrive: HardDrive,
  send: Send,
  info: Info,
  xCircle: XCircle,
  edit2: Edit2,
  logIn: LogIn,
  trendingUp: TrendingUp,
  trendingDown: TrendingDown,
  logOut: LogOut,
  server: Server,
  tag: Tag,
  layoutList: LayoutList,
  userCheck: UserCheck,
  gripVertical: GripVertical,
  messageSquare: MessageSquare
};